server:
  binding:
    ip: 0.0.0.0
    port: 9000

auth:
  me_url: https://example.org
  validate_token_url: https://tokens.indieauth.com/token

micropub:
  media:
    # Public URL at which the media uploaded by this micropub server
    # can be viewed. This must end with a trailing slash, as it will
    # be combined with the object key to complete the media permalink.
    public_url: https://media.example.org/

    # Configuration for the S3 (or S3-compatible) object store to use
    # for uploading media (either files attached to a create request,
    # or files uploaded through the media endpoint).
    s3:
      access_key_id: "replaceme"
      secret_access_key: "replaceme"
      region: ap-southeast-1
      bucket: my-bucket
      endpoint: https://s3.ap-southeast-1.amazonaws.com

  content:
    # Public URL at which the content published by this micropub server
    # can be viewed. Might not be the same as Scribble's URL! This must
    # end with a trailing slash, as it will be combined with the completed
    # path pattern. This is used to construct URLs returned by the micropub
    # endpoint to a micropub client, so that the client knows where to redirect.
    public_url: https://example.org/

    # The path pattern used for creating a content permalink URL. Some
    # variables will be automatically replaced upon creation, namely:
    # {year} - the current year, four digits
    # {month} - the current month, two digits zero-padded
    # {day} - the current day, two digits zero-padded
    # {slug} - the slug of the item (derived from mp-slug, or auto-generated uuid)
    path_pattern: "{year}/{month}/{day}/{slug}"
    
    # Configuration for the git storage driven by this micropub server.
    # This repository should be owned by Scribble! If you commit to this
    # repository while Scribble is running, it may result in undefined behavior.
    # When linking to your website repository, please use a submodule and set up
    # a CI/CD job linking the content repository with the website repository.
    # For example, when a push is detected on the content repository, trigger
    # the website repository to sync submodules, rebuild, and then deploy.
    git:
      repository: git@github.com:my-username/my-scribble-content
      key_path: "~/.ssh/id_rsa"
      username: ~
      password: my_passphrase
      branch: ~
 